### ISSUE TITLE
Object creation inside thread doesn't work?

### ISSUE THREAD

**Issue by omegadan** [mattn/mruby-thread#28]
When I do this:

```ruby
class Do
	def something()
		puts "something"
	end
end

dot = Thread.new do

	puts "Before"
    dm = Do.new
    puts "After"
	dm.something
	puts "Never"
end

dot.join
```

The output is only "Before". Have I misunderstood something about the limitations of this module? If so, what are the limitations?

**Comment by mattn** [comment]
Yes, I'ts limitation currently. Class object is not possible to migrate between threads.

**Comment by omegadan** [comment]
I see. Thank you kindly :)

**Comment by mowrang** [comment]
What work around do you suggest for this limitation?

**Comment by mattn** [comment]
When gems are loaded at phase of initialization, Class is loaded as same as main thread. When then class is placed in the source (not in mrbgems), it's not possible to pass Class into the thread.
White-listed classes are specified as hardcoded in below.
https://github.com/mattn/mruby-thread/blob/master/src/mrb_thread.c#L126
