### ISSUE TITLE
What pthread_kill is doing?

### ISSUE THREAD

**Issue by murasesyuka** [mattn/mruby-thread#30]
there is one question.

what mean under the code?

```c
pthread_kill(context->thread, 0);
```

  if checking thread_id valid or thread exist, I think it need return value.
for example

```c
if (pthread_kill(context->thread, 0) == ESRCH){ /*  Not a valid thread  */ }
```

**Comment by mattn** [comment]
do you mean pthread_kill in mrb_thread_kill ?

**Comment by murasesyuka** [comment]
Both in mrb_thread_kill () and in mrb_thread_context_free ().

**Comment by mattn** [comment]
This is complementary for terminating thread.

**Comment by murasesyuka** [comment]
thank you for fix
