### ISSUE TITLE
Are you sure this save outside of cycle and restore inside is correct?

### ISSUE THREAD

**Issue by vobloeb** [mattn/mruby-thread#70]
https://github.com/mattn/mruby-thread/blob/cfcfab303e48d40c2327e641c81e3d6899268580/src/mrb_thread.c#L454-L457

**Comment by mattn** [comment]
What do you mean?

**Comment by vobloeb** [comment]
I mean complex values fail to migrate
```ruby
  a = Thread.new {
    [:fancylines, [
      {:text=>"text1", :color_bg=>44, :color_fg=>36, :color_icon=>:red, :icon=>"#"},
      {:text=>"text2", :color_bg=>44, :color_fg=>36, :color_icon=>:red, :icon=>"#"},
      {:text=>"text3", :color_bg=>44, :color_fg=>36, :color_icon=>:red, :icon=>"#"}
    ]]
  }
  p a.join
```

result in 
```
[:fancylines, [{:text=>"text1", :color_bg=>36, :color_fg=>:red, :color_icon=>nil, :icon=>"#"}, {:text=>"text2", :color_bg=>36, :color_fg=>:red, :color_icon=>nil, :icon=>"#"}, {:text=>"text3", :color_bg=>36, :color_fg=>:red, :color_icon=>nil, :icon=>"#"}]]
```

note that some values become `nil`

**Comment by vobloeb** [comment]
Ah, it is another bug

https://github.com/mattn/mruby-thread/blob/cfcfab303e48d40c2327e641c81e3d6899268580/src/mrb_thread.c#L471-L472


`k` is on `mrb2` but used with `mrb` in `mrb_hash_get(mrb, v, k)`

it works well with
```c
      mrb_value k1 = mrb_ary_entry(ka, i);
      mrb_value k2 = mrb_thread_migrate_value(mrb, k1, mrb2);

      mrb_value o1 = mrb_hash_get(mrb, v, k1);
      mrb_value o2 = mrb_thread_migrate_value(mrb, o1, mrb2);

      mrb_hash_set(mrb2, nv, k2, o2);
```

**Comment by mattn** [comment]
Ah, could you please send me pull-request?

**Comment by vobloeb** [comment]
Unfortunately, it is not enough.
I still observe memory corruption and random crashes migrating complex structures.

**Comment by vobloeb** [comment]
This crashes almost always, on any mruby from `2.1.2` to `3.3.0`, with debug and release builds.
My fix does not help either

```ruby
$q = Queue.new
$t = Thread.new($q) do |q|
  loop do
    op = q.shift
  end
end

(0 ... 100).each {|x|
  $q.push [ "abcde"*x, [{text: "msg #{x}", color: :red, a: [[x]]*x}] ]
}
p "done"
```

**Comment by vobloeb** [comment]
Well, `Queue` should have its own `mrb_state`.

Currently, `Queue`'s operations do `mrb_thread_migrate_value` between the current `mrb_state` and another which is running in background thread, that results in memory corruption
